version: '3.9'

services:
  api:
    build: .
    user: '1000:984'
    ports:
      - '3001:3001'
    restart: always
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    environment:
      DATABASE_URL: 'postgresql://foo:noTSoStr0ng@localhost:5432/athazagoraphobia?schema=public'
      NODE_ENV: 'development'
      HOST: '0.0.0.0'
      PORT: 3001
    depends_on:
      - db
  db:
    image: postgres:13.3
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'noTSoStr0ng'
      POSTGRES_USER: 'foo'
      POSTGRES_DB: 'athazagoraphobia'

volumes:
  pgdata: {}
