version: '3.9'

services:
  api:
    build: .
    user: '1000:984'
    ports:
      - '3001:3000'
    restart: always
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    environment:
      DATABASE_URL: 'postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}'
      NODE_ENV: '${NODE_ENV}'
      HOST: '0.0.0.0'
      PORT: 3000
    depends_on:
      - db
  db:
    image: postgres:13.3
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_DB: '${POSTGRES_DB}'

volumes:
  pgdata: {}
